version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: github.com/brenogmrs/go-gin-api-db
    container_name: go-gin-api-db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/go-gin-api
    volumes:
      - go-gin-api:/var/lib/postgresql/data

volumes:
  go-gin-api: